# CombatExpanded Config

### IMPORTANT: to make config values apply in game, just do /ce reload ###

plugin-enabled: true       # Can enable/disable the plugin in here or in game with /ce enable|disable

grapple:
  pending-expire: 100      # Time (in ticks) before a grapple expires if not activated
  timeout: 60              # Time (in ticks) before grapple forcefully cancels when pulling

dash:
  speed: 2.0           # Dash speeds
  air-speed: 1.0       # Air-Dash speeds
  cooldown: 5          # Time (in ticks) before you can dash after a previous dash
  damage: 7.5          # Damage the dash deals

slam:
  fall-speed: -3.0           # Slam speeds
  aoe-radius: 5.0            # Radius of slam to detect/ damage mobs
  knockback-strength: 2.0    # How far nearby mobs get knocked back
  damage: 15.0               # Damage the slam deals

stamina:
  max-stamina: 4       # Maximum stamina you can have
  dash-cost: 1         # Stamina cost of dash
  slam-cost: 1         # Stamina cost of slam

  normal-regen: 0.33  # Stamina regen per second when moving
  still-regen: 1.0   # Stamina regen per second when still